apiVersion: v1
kind: Pod
metadata:
  name: jenkins-node-pg-0
  namespace: jenkins2025
  labels:
    app.kubernetes.io/name: jenkins-node-pg
spec:
  volumes:
    - name: rsa-keys
      configMap:
        name: rsa-keys
        defaultMode: 384
    - name: dind-storage
      emptyDir: {}
  containers:
    - name: compiler
      image: etendo/compiler_jenkins:1.0.7-jdk.17.0.13
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
      securityContext:
        privileged: true
        runAsUser: 0
      ports:
        - name: ssh
          containerPort: 22
          protocol: TCP
        - name: visualvm
          containerPort: 8000
          protocol: TCP
      resources:
        requests:
          cpu: 1072m
          memory: 4000Mi
          ephemeral-storage: 1Gi
        limits:
          cpu: 2072m
          memory: 6500Mi
          ephemeral-storage: 5Gi
      volumeMounts:
        - name: rsa-keys
          mountPath: /root/.ssh/
      lifecycle:
        postStart:
          exec:
            command:
              - bash
              - -lc
              - |
                set -e
                apt-get update -y
                command -v docker >/dev/null || apt-get install -y docker.io
                apt-get install -y curl
      imagePullPolicy: IfNotPresent
    - name: dind
      image: docker:25-dind
      securityContext:
        privileged: true
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
      args:
        - --mtu=1450
        - --storage-driver=overlay2
      resources:
        requests:
          cpu: 500m
          memory: 1000Mi
          ephemeral-storage: 1Gi
        limits:
          cpu: 1000m
          memory: 2000Mi
          ephemeral-storage: 5Gi
      volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  serviceAccountName: default
  serviceAccount: default
  automountServiceAccountToken: false
  securityContext: {}
