services:
  db:
    env_file: ".env"
    image: postgres:14
    environment:
      POSTGRES_USER: ${BBDD_SYSTEMUSER}
      POSTGRES_PASSWORD: ${BBDD_SYSTEMPASSWORD}
      POSTGRES_DB: ${BBDD_SID}
    ports:
      - "${BBDD_PORT}:5432"
    networks:
      - etendo
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
